import Image from "next/image";
import CurrentPath from "@/components/get-pathname";
import GoBack from "@/components/btn-back";
import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "Error 404",
	description: "Generated by page not-found",
	robots: "noindex, nofollow",
};

export default function NotFound() {
	return (
		<section className="container-fluid my-10 max-sm:px-2">
			<Image
				src="/images/err404.svg"
				width={330}
				height={330}
				alt="error-icon"
				className="mx-auto max-w-[20rem]"
			/>
			<div className="flex flex-col items-center justify-center w-full text-center">
				<h3 className="font-bold text-h3">
					File or path : <CurrentPath /> Not Found
				</h3>
				<h4 className="font-semibold text-h4 italic">Resource Error</h4>
				<p className="mx-auto">
					<GoBack />
				</p>
			</div>
		</section>
	);
}
